name = "mabmabmabmabmab/llm"
version = "0.1.0"
description = "A compact Maid library with no locals whatsoever."
authors = ["Gas"]
repository = "https://github.com/MabMabMabMabMab/llm"
license = "MIT"

includes = [
    "LICENSE",
    "README.md",
    "pesde.toml",
    "src/init.luau",
]

[target]
lib = "src/init.luau"
environment = "roblox"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"
